/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 89118bc208f0512a1b93c210b8b8dc71)
interface __BaseEnv_Env {
  AI: Ai;
  TavusThinkAgent: DurableObjectNamespace<
    import("./src/server").TavusThinkAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TavusThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
