/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 1abe2a16df52982d27d3b3edb5b41498)
interface __BaseEnv_Env {
  AI: Ai;
  MyVoiceAgent: DurableObjectNamespace<import("./src/server").MyVoiceAgent>;
  MyThinkAgent: DurableObjectNamespace<import("./src/server").MyThinkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyVoiceAgent" | "MyThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
