/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e1140af32e8c2d3a3f33b37ef2c521f9)
interface __BaseEnv_Env {
  AI: Ai;
  MyThinkAgent: DurableObjectNamespace<import("./src/server").MyThinkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
