/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 69d70913515a4897dc7e2b58e8a8b069)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	RETAIL_MCP_SERVER_URL: "https://wpros-mcp.agenticflows.workers.dev/retail/mcp";
	MyVoiceAgent: DurableObjectNamespace<import("./src/index").MyVoiceAgent>;
	MyThinkAgent: DurableObjectNamespace<import("./src/index").MyThinkAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyVoiceAgent" | "MyThinkAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RETAIL_MCP_SERVER_URL">> {}
}
