/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 7c79843cf829c587fbd4785b3691e99a)
interface __BaseEnv_Env {
  AI: Ai;
  MCP_SERVER_URL: "https://signalwire-mcp-voice-agent-example.agenticflows.workers.dev/mcp";
  RETAIL_MCP_SERVER_URL: "https://wpros-mcp.agenticflows.workers.dev/retail/mcp";
  MyVoiceAgent: DurableObjectNamespace<import("./src/index").MyVoiceAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "MCP_SERVER_URL" | "RETAIL_MCP_SERVER_URL">
  > {}
}
